<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="WorkflowEngine.Tests" />
    <InternalsVisibleTo Include="IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\RadiusClaim.Contracts\RadiusClaim.Contracts.csproj" />
    <ProjectReference Include="..\shared\RadiusClaim.Dapr\RadiusClaim.Dapr.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapr.AspNetCore" Version="1.17.5" />
    <PackageReference Include="Dapr.Workflow" Version="1.17.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
